extends:
  - airbnb
  - prettier
  - prettier/react
  - prettier/standard

parser: "babel-eslint"

plugins:
  - prettier
  - react
  - react-hooks
  - standard

rules:
  # Prettier
  prettier/prettier: error

  import/no-named-as-default: off
  react/jsx-props-no-spreading: off
  no-param-reassign: off

env:
  browser: true
  node: true
  es6: true
